# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5577441ac6fcf33e0040153646a7f0aca097d094add70e0f72d863c1d1cd8ff2532e67fe8938dd334d0029e1520bdacc23e85b440689294dbea902f7f3cef754

test:
  secret_key_base: 78523f5333efa714398418749886a248ffe5956952b61dde5bde0d413c609e5854138aea423ec7c20084ec484539cc600ab0a2e57ed45f1af75c401aee4ccf22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
